import { useState } from 'react'
import { Link } from 'react-router-dom'
import s from './PAGE.module.css'

const FEATURES = [
  {
    icon: '📁',
    title: 'Filesystem routing',
    desc: 'Routes are derived from your folder structure. No manual route config files to maintain.',
  },
  {
    icon: '⚡',
    title: 'Zero runtime',
    desc: 'The plugin generates a plain .ts file on disk at Vite startup. Nothing runs at request time.',
  },
  {
    icon: '🔀',
    title: 'React Router v6',
    desc: 'Full support for nested layouts, index routes, dynamic segments, and error boundaries.',
  },
  {
    icon: '🦥',
    title: 'Lazy loading',
    desc: 'Name a file PAGE.lazy.tsx and it is automatically wrapped with React.lazy() and code-split.',
  },
]

const FILE_TREE = `\
src/pages/
  LAYOUT.tsx
  BOUNDARY.tsx
  PAGE.tsx
  ERROR.tsx
  about/PAGE.tsx
  contact/PAGE.tsx
  user/PAGE.tsx
  user/[id]/PAGE.tsx      ← [param] → :param
  blog/
    LAYOUT.tsx
    BOUNDARY.tsx
    PAGE.tsx
    ERROR.tsx
    intro/PAGE.lazy.tsx
    routing/PAGE.lazy.tsx
    error/PAGE.lazy.tsx
    []/PAGE.tsx            ← [] → * (catch-all)
`

const INTERPRETED = `\
/                    [LAYOUT]  [BOUNDARY=errorElement]
├── /                [PAGE]    [ERROR=errorElement]
├── /about           [PAGE]
├── /contact         [PAGE]
├── /user            [PAGE]
│   └── /user/:id    [PAGE]
└── /blog            [LAYOUT]  [BOUNDARY=errorElement]
    ├── /blog        [PAGE]    [ERROR=errorElement]
    ├── /blog/intro             [PAGE.lazy]
    ├── /blog/routing           [PAGE.lazy]
    ├── /blog/error             [PAGE.lazy]
    └── /blog/*      [PAGE]    ← catch-all (blog/[]/PAGE.tsx)`

const CONFIG_MODE = `\
// src/routes.ts  (generated by the plugin)
// imports....
export default [
  {
    path: "/",
    element: createElement(_LAYOUT),
    errorElement: createElement(_BOUNDARY),
    children: [
      { index: true,     element: createElement(_PAGE),        errorElement: createElement(_ERROR), },
      { path: "about",   element: createElement(_about_PAGE)   },
      { path: "contact", element: createElement(_contact_PAGE) },
      {
        path: "user",
        children: [
          { index: true,  element: createElement(_user_PAGE)    },
          { path: ":id",  element: createElement(_user_id_PAGE) },
        ],
      },
      {
        path: "blog",
        element: createElement(_blog_LAYOUT),
        errorElement: createElement(_blog_BOUNDARY),
        children: [
          { index: true,     element: createElement(_blog_PAGE),             errorElement: createElement(_blog_ERROR), },
          { path: "intro",   element: createElement(_blog_intro_PAGE_lazy)   },
          { path: "routing", element: createElement(_blog_routing_PAGE_lazy) },
          { path: "error",   element: createElement(_blog_error_PAGE_lazy)   },
          { path: "*",       element: createElement(_blog_notFound_PAGE)      },
        ],
      },
    ],
  },
]`

const ELEMENT_MODE = `\
<Routes>
  <Route path="/"           element={<RootLayout />}     errorElement={<RootBoundary />}>
    <Route index            element={<HomePage />}       errorElement={<RootError />}  />
    <Route path="about"     element={<AboutPage />}   />
    <Route path="contact"   element={<ContactPage />} />
    <Route path="user">
      <Route index          element={<UserListPage />}   />
      <Route path=":id"     element={<UserDetailPage />} />
    </Route>
    <Route path="blog"      element={<BlogLayout />}      errorElement={<BlogBoundary />}>
      <Route index          element={<BlogIndexPage />}   errorElement={<BlogError />}  />
      <Route path="intro"   element={<BlogIntroLazy />}   />
      <Route path="routing" element={<BlogRoutingLazy />} />
      <Route path="error"   element={<BlogErrorLazy />}   />
      <Route path="*"       element={<BlogNotFound />}    />
    </Route>
  </Route>
</Routes>`

type Tab = 'tree' | 'interpreted' | 'config' | 'element'

const TABS: { id: Tab; label: string }[] = [
  { id: 'tree',        label: 'File tree' },
  { id: 'interpreted', label: 'Interpreted' },
  { id: 'config',      label: 'Config (routes.ts)' },
  { id: 'element',     label: 'JSX element' },
]

function RouteViewer() {
  const [tab, setTab] = useState<Tab>('tree')
  const content: Record<Tab, string> = {
    tree:        FILE_TREE,
    interpreted: INTERPRETED,
    config:      CONFIG_MODE,
    element:     ELEMENT_MODE,
  }
  return (
    <div>
      <div className={s.tabs}>
        {TABS.map(t => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={[s.tab, tab === t.id ? s.tabActive : ''].join(' ')}
          >
            {t.label}
          </button>
        ))}
      </div>
      <pre className={s.pre}>{content[tab]}</pre>
    </div>
  )
}

export default function HomePage() {
  const [crash, setCrash] = useState(false)
  if (crash) throw new Error('Intentional page crash — caught by ERROR.tsx')

  return (
    <div>
      <section className={s.hero}>
        <div className={s.heroBadge}>vite-plugin-web-routes</div>
        <h1 className={s.heroTitle}>
          <span className={s.red}>Semantic</span> filesystem routing<br />for React Router v6
        </h1>
        <p className={s.heroSub}>
          Place files. Name them <code>PAGE.tsx</code>. Get routes.
          No configuration, no boilerplate — just a folder structure.
        </p>
        <div className={s.install}>
          <span className={s.installPrompt}>$</span>
          <code className={s.installCmd}>npm install -D vite-plugin-web-routes</code>
        </div>
        <div className={s.heroBtns}>
          <Link to="/about" className={s.btnPrimary}>Get Started →</Link>
          <Link to="/blog" className={s.btnSecondary}>Read the Guide</Link>
        </div>
      </section>

      <section className={s.grid}>
        {FEATURES.map((f) => (
          <div key={f.title} className={s.card}>
            <span className={s.cardIcon}>{f.icon}</span>
            <h3 className={s.cardTitle}>{f.title}</h3>
            <p className={s.cardDesc}>{f.desc}</p>
          </div>
        ))}
      </section>

      <section className={s.section}>
        <h2 className={s.sectionTitle}>File structure → Routes</h2>
        <RouteViewer />
      </section>

      <section className={s.section}>
        <h2 className={s.sectionTitle}>Error boundary demo</h2>
        <div className={s.demoRow}>
          <div className={s.demoCard}>
            <p className={s.demoLabel}>Page error → ERROR</p>
            <p className={s.demoDesc}>The layout (header, footer) <strong>stays visible</strong>.</p>
            <button onClick={() => setCrash(true)} className={s.throwBtn}>
              Throw page error
            </button>
          </div>
          <div className={s.demoCard}>
            <p className={s.demoLabel}>Layout error → BOUNDARY</p>
            <p className={s.demoDesc}>The <strong>entire layout disappears</strong>.</p>
            <p className={s.demoHint}>↓ button in the footer</p>
          </div>
        </div>
      </section>
    </div>
  )
}
